package com.bigbuttons.remote
import android.app.*
import android.content.Intent
import android.graphics.Typeface
import android.os.Bundle
import android.view.Gravity
import android.view.View
import android.widget.*
class PageManagerActivity:Activity(){private var modeIndex=0;override fun onCreate(savedInstanceState:Bundle?){super.onCreate(savedInstanceState);AppPrefs.ensureMigrated(this);modeIndex=intent.getIntExtra("mode_index",AppPrefs.activeModeIndex(this)).coerceIn(0,AppPrefs.MODE_COUNT-1);render()};override fun onResume(){super.onResume();if(!isFinishing)render()};private fun render(){val mode=AppPrefs.mode(this,modeIndex);val scroll=ScrollView(this).apply{setBackgroundColor(AppColors.Background)};val root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};applySystemBarPadding(root,16,14);scroll.addView(root,FrameLayout.LayoutParams(FrameLayout.LayoutParams.MATCH_PARENT,FrameLayout.LayoutParams.WRAP_CONTENT));root.addView(TextView(this).apply{text="Buttons & pages";setTextColor(AppColors.Text);textSize=27f;setTypeface(typeface,Typeface.BOLD)});root.addView(TextView(this).apply{text="${mode.name} · tap a page to edit its six buttons.";setTextColor(AppColors.Muted);textSize=14f;setPadding(0,dp(4),0,dp(16))});mode.pages.forEach{page->val configured=page.buttons.count{when(it.actionType){ButtonActionType.COMMAND->it.value.isNotBlank();ButtonActionType.PAGE->it.value.isNotBlank();ButtonActionType.BACK->true}};val card=Button(this).apply{text="${page.name}\n${if(page.id==AppPrefs.MAIN_PAGE_ID)"Main page · " else ""}$configured of 6 configured";gravity=Gravity.CENTER_VERTICAL;textAlignment=View.TEXT_ALIGNMENT_VIEW_START;textSize=17f;setTextColor(AppColors.Text);setTypeface(typeface,Typeface.BOLD);isAllCaps=false;minHeight=0;minWidth=0;setPadding(dp(16),dp(12),dp(16),dp(12));background=rippleBackground(AppColors.SurfaceRaised,18,AppColors.Border);setOnClickListener{startActivity(Intent(this@PageManagerActivity,PageEditorActivity::class.java).putExtra("mode_index",modeIndex).putExtra("page_id",page.id))}};root.addView(card,LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,dp(86)).apply{bottomMargin=dp(10)})};root.addView(Button(this).apply{text="ADD PAGE";setTextColor(AppColors.Text);setTypeface(typeface,Typeface.BOLD);isAllCaps=false;background=rippleBackground(AppColors.AccentDark,16,AppColors.Accent);setOnClickListener{showAddPageDialog()}},LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,dp(52)).apply{topMargin=dp(4);bottomMargin=dp(10)});root.addView(Button(this).apply{text="DONE";setTextColor(AppColors.Text);setTypeface(typeface,Typeface.BOLD);isAllCaps=false;background=rippleBackground(AppColors.Surface,16,AppColors.Border);setOnClickListener{finish()}},LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,dp(52)).apply{bottomMargin=dp(16)});setContentView(scroll)}
private fun showAddPageDialog(){val field=EditText(this).apply{hint="Page name, e.g. Playlists";setSingleLine(true);setPadding(dp(20),dp(10),dp(20),dp(10))};val container=FrameLayout(this).apply{setPadding(dp(8),0,dp(8),0);addView(field,FrameLayout.LayoutParams(FrameLayout.LayoutParams.MATCH_PARENT,FrameLayout.LayoutParams.WRAP_CONTENT))};AlertDialog.Builder(this).setTitle("Add page").setView(container).setNegativeButton("CANCEL",null).setPositiveButton("CREATE"){_,_->val page=AppPrefs.addPage(this,modeIndex,field.text.toString());startActivity(Intent(this,PageEditorActivity::class.java).putExtra("mode_index",modeIndex).putExtra("page_id",page.id))}.show()}}
