package com.bigbuttons.remote

import android.app.*
import android.content.res.ColorStateList
import android.graphics.Typeface
import android.os.Bundle
import android.view.*
import android.widget.*

class PageEditorActivity:Activity(){
    private var modeIndex=0;private var pageId=AppPrefs.MAIN_PAGE_ID;private lateinit var pageNameField:EditText;private lateinit var workingButtons:MutableList<BigButtonConfig>
    override fun onCreate(savedInstanceState:Bundle?){super.onCreate(savedInstanceState);AppPrefs.ensureMigrated(this);modeIndex=intent.getIntExtra("mode_index",AppPrefs.activeModeIndex(this)).coerceIn(0,AppPrefs.MODE_COUNT-1);pageId=intent.getStringExtra("page_id")?:AppPrefs.MAIN_PAGE_ID;loadAndRender()}
    private fun loadAndRender(){val page=AppPrefs.pages(this,modeIndex).firstOrNull{it.id==pageId}?:run{finish();return};workingButtons=page.buttons.toMutableList();render(page)}
    private fun render(page:PageConfig){val mode=AppPrefs.mode(this,modeIndex);val scroll=ScrollView(this).apply{setBackgroundColor(AppColors.Background)};val root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};applySystemBarPadding(root,16,14);scroll.addView(root,FrameLayout.LayoutParams(FrameLayout.LayoutParams.MATCH_PARENT,FrameLayout.LayoutParams.WRAP_CONTENT));val titleRow=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER_VERTICAL};titleRow.addView(TextView(this).apply{text="Edit page";setTextColor(AppColors.Text);textSize=25f;setTypeface(typeface,Typeface.BOLD)},LinearLayout.LayoutParams(0,dp(54),1f));titleRow.addView(Button(this).apply{text="SAVE";setTextColor(AppColors.Text);setTypeface(typeface,Typeface.BOLD);isAllCaps=false;background=rippleBackground(AppColors.AccentDark,14,AppColors.Accent);setOnClickListener{savePage();Toast.makeText(this@PageEditorActivity,"Saved",Toast.LENGTH_SHORT).show();finish()}},LinearLayout.LayoutParams(dp(92),dp(46)));root.addView(titleRow);root.addView(TextView(this).apply{text=mode.name;setTextColor(AppColors.Muted);textSize=13f;setPadding(0,0,0,dp(8))});root.addView(label("Page name"));pageNameField=EditText(this).apply{setText(page.name);setTextColor(AppColors.Text);setHintTextColor(AppColors.Muted);setSingleLine(true);backgroundTintList=ColorStateList.valueOf(AppColors.Muted)};root.addView(pageNameField,LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,dp(50)).apply{bottomMargin=dp(10)});root.addView(TextView(this).apply{text="Tap a button below to change what it does.";setTextColor(AppColors.Muted);textSize=14f;setPadding(0,0,0,dp(10))});val preview=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};root.addView(preview)
        repeat(3){r->val row=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL};preview.addView(row,LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,dp(120)));repeat(2){c->val i=r*2+c;val config=workingButtons[i];val summary=when(config.actionType){ButtonActionType.COMMAND->if(config.value.isBlank())"Empty" else "Command: ${config.value}";ButtonActionType.PAGE->"Opens: ${mode.pages.firstOrNull{it.id==config.value}?.name?:"Missing page"}";ButtonActionType.BACK->"Go back"};val b=Button(this).apply{text=if(config.label.isBlank())"SET BUTTON\n$summary" else "${config.label}\n$summary";textSize=15f;setTextColor(AppColors.Text);setTypeface(typeface,Typeface.BOLD);gravity=Gravity.CENTER;isAllCaps=false;minHeight=0;minWidth=0;background=rippleBackground(AppColors.SurfaceRaised,18,AppColors.Border);setOnClickListener{showButtonEditor(i)}};row.addView(b,LinearLayout.LayoutParams(0,LinearLayout.LayoutParams.MATCH_PARENT,1f).apply{val g=dp(5);setMargins(g,g,g,g)})}}
        if(page.id!=AppPrefs.MAIN_PAGE_ID)root.addView(Button(this).apply{text="DELETE PAGE";setTextColor(AppColors.Text);setTypeface(typeface,Typeface.BOLD);isAllCaps=false;background=rippleBackground(AppColors.Danger,16);setOnClickListener{AlertDialog.Builder(this@PageEditorActivity).setTitle("Delete ${page.name}?").setMessage("Any buttons that open this page will be cleared.").setNegativeButton("CANCEL",null).setPositiveButton("DELETE"){_,_->AppPrefs.deletePage(this@PageEditorActivity,modeIndex,page.id);finish()}.show()}},LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,dp(52)).apply{topMargin=dp(16);bottomMargin=dp(12)}) else root.addView(TextView(this).apply{text="The Main page cannot be deleted.";setTextColor(AppColors.Muted);textSize=13f;setPadding(0,dp(14),0,dp(14))});setContentView(scroll)}
    private fun showButtonEditor(index:Int){val current=workingButtons[index];val mode=AppPrefs.mode(this,modeIndex);val root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(20),dp(6),dp(20),0)};root.addView(label("Button label"));val labelField=EditText(this).apply{setText(current.label);hint="e.g. Playlists";setSingleLine(true)};root.addView(labelField);root.addView(label("Tap action"));val actionSpinner=Spinner(this);val options=listOf("Send command","Open page","Go back");actionSpinner.adapter=ArrayAdapter(this,android.R.layout.simple_spinner_dropdown_item,options);actionSpinner.setSelection(when(current.actionType){ButtonActionType.COMMAND->0;ButtonActionType.PAGE->1;ButtonActionType.BACK->2});root.addView(actionSpinner);val detail=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(0,dp(8),0,0)};root.addView(detail);var commandField:EditText?=null;var pageSpinner:Spinner?=null;var destinations:List<PageConfig> = emptyList()
        fun rebuild(pos:Int){detail.removeAllViews();commandField=null;pageSpinner=null;destinations=emptyList();when(pos){0->{detail.addView(label("Command"));commandField=EditText(this@PageEditorActivity).apply{setText(if(current.actionType==ButtonActionType.COMMAND)current.value else "");hint="e.g. driving_playlist";setSingleLine(true)};detail.addView(commandField)};1->{detail.addView(label("Open page"));destinations=mode.pages.filter{it.id!=pageId};if(destinations.isEmpty())detail.addView(TextView(this@PageEditorActivity).apply{text="Create another page first, then return here.";setTextColor(AppColors.Muted);textSize=14f;setPadding(0,dp(6),0,dp(6))})else{pageSpinner=Spinner(this@PageEditorActivity).apply{adapter=ArrayAdapter(this@PageEditorActivity,android.R.layout.simple_spinner_dropdown_item,destinations.map{it.name});val ci=destinations.indexOfFirst{it.id==current.value};setSelection(if(ci>=0)ci else 0)};detail.addView(pageSpinner)}};2->detail.addView(TextView(this@PageEditorActivity).apply{text="This button returns to the previous page.";setTextColor(AppColors.Muted);textSize=14f;setPadding(0,dp(6),0,dp(6))})}}
        actionSpinner.onItemSelectedListener=object:AdapterView.OnItemSelectedListener{override fun onItemSelected(parent:AdapterView<*>?,view:View?,position:Int,id:Long){rebuild(position)};override fun onNothingSelected(parent:AdapterView<*>?)=Unit};rebuild(actionSpinner.selectedItemPosition);val dialog=AlertDialog.Builder(this).setTitle("Button ${index+1}").setView(root).setNegativeButton("CANCEL",null).setPositiveButton("SAVE",null).create();dialog.setOnShowListener{dialog.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener{val type=when(actionSpinner.selectedItemPosition){1->ButtonActionType.PAGE;2->ButtonActionType.BACK;else->ButtonActionType.COMMAND};val value=when(type){ButtonActionType.COMMAND->commandField?.text?.toString()?.trim().orEmpty();ButtonActionType.PAGE->{if(destinations.isEmpty()){Toast.makeText(this,"Create another page first",Toast.LENGTH_SHORT).show();return@setOnClickListener};destinations[(pageSpinner?.selectedItemPosition?:0).coerceIn(0,destinations.lastIndex)].id};ButtonActionType.BACK->""};workingButtons[index]=BigButtonConfig(labelField.text.toString().trim(),type,value);savePage();dialog.dismiss();loadAndRender()}};dialog.show()}
    private fun savePage(){val pages=AppPrefs.pages(this,modeIndex).toMutableList();val i=pages.indexOfFirst{it.id==pageId};if(i<0)return;pages[i]=pages[i].copy(name=pageNameField.text.toString().trim().ifBlank{if(pageId==AppPrefs.MAIN_PAGE_ID)"Main" else "Page"},buttons=workingButtons.toList());AppPrefs.savePages(this,modeIndex,pages)}
    private fun label(t:String)=TextView(this).apply{text=t;setTextColor(AppColors.Text);textSize=13f;setTypeface(typeface,Typeface.BOLD);setPadding(0,dp(7),0,dp(2))}
}
