package com.bigbuttons.remote

import android.app.*
import android.content.Intent
import android.content.res.ColorStateList
import android.graphics.Typeface
import android.os.Bundle
import android.text.InputType
import android.view.Gravity
import android.view.View
import android.widget.*

class SettingsActivity:Activity(){
    private var modeIndex=0
    private lateinit var nameField:EditText; private lateinit var useAutomateSwitch:Switch; private lateinit var actionField:EditText; private lateinit var extraKeyField:EditText; private lateinit var packageField:EditText; private lateinit var automateHelpButton:Button; private lateinit var startupEnabledSwitch:Switch; private lateinit var wakeTargetSwitch:Switch; private lateinit var startupDelayField:EditText; private lateinit var startupCommandField:EditText; private lateinit var returnSwitch:Switch; private lateinit var vibrationSwitch:Switch; private lateinit var awakeSwitch:Switch
    override fun onCreate(savedInstanceState:Bundle?){super.onCreate(savedInstanceState);AppPrefs.ensureMigrated(this);modeIndex=AppPrefs.activeModeIndex(this);render()}
    override fun onResume(){super.onResume();if(::nameField.isInitialized)render()}
    private fun render(){val mode=AppPrefs.mode(this,modeIndex);val global=AppPrefs.global(this);val scroll=ScrollView(this).apply{setBackgroundColor(AppColors.Background)};val root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};applySystemBarPadding(root,16,12);scroll.addView(root,FrameLayout.LayoutParams(FrameLayout.LayoutParams.MATCH_PARENT,FrameLayout.LayoutParams.WRAP_CONTENT));val top=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER_VERTICAL};top.addView(TextView(this).apply{text="Settings";setTextColor(AppColors.Text);textSize=26f;setTypeface(typeface,Typeface.BOLD)},LinearLayout.LayoutParams(0,dp(58),1f));top.addView(Button(this).apply{text="SAVE";setTextColor(AppColors.Text);setTypeface(typeface,Typeface.BOLD);isAllCaps=false;background=rippleBackground(AppColors.AccentDark,14,AppColors.Accent);setOnClickListener{if(saveSettingsOnly()){Toast.makeText(this@SettingsActivity,"Saved",Toast.LENGTH_SHORT).show();finish()}}},LinearLayout.LayoutParams(dp(92),dp(46)));root.addView(top)
        root.addView(sectionTitle("Mode"));root.addView(sectionCard().apply{nameField=field("Mode name",mode.name);addView(nameField.tag as View)})
        root.addView(sectionTitle("Startup"));root.addView(sectionCard().apply{startupEnabledSwitch=switchRow("Run startup when this mode opens",mode.startupEnabled);wakeTargetSwitch=switchRow("Open receiver app first",mode.wakeTarget);startupDelayField=field("Startup delay",mode.startupDelayMs.toString(),"milliseconds",true);startupCommandField=field("Startup command",mode.startupCommand,"Example: solo_start");returnSwitch=switchRow("Return to BigButtons after opening receiver",mode.returnToBigButtons);addView(startupEnabledSwitch);addView(wakeTargetSwitch);addView(startupDelayField.tag as View);addView(startupCommandField.tag as View);addView(returnSwitch)})
        root.addView(sectionTitle("Integration"));root.addView(sectionCard().apply{useAutomateSwitch=switchRow("Use Automate integration",mode.useAutomateIntegration);addView(useAutomateSwitch);automateHelpButton=Button(this@SettingsActivity).apply{text="AUTOMATE SETUP INSTRUCTIONS";setTextColor(AppColors.Text);setTypeface(typeface,Typeface.BOLD);isAllCaps=false;background=rippleBackground(AppColors.AccentDark,14,AppColors.Accent);setOnClickListener{showAutomateSetupDialog()}};addView(automateHelpButton,LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,dp(48)).apply{topMargin=dp(8)})})
        root.addView(sectionTitle("Receiver"));root.addView(sectionCard().apply{actionField=field("Broadcast action",mode.broadcastAction,"Example: com.example.COMMAND");extraKeyField=field("Command key",mode.extraKey,"The extra containing the command value");packageField=field("Target app package",mode.targetPackage,"Example: com.llamalab.automate");addView(actionField.tag as View);addView(extraKeyField.tag as View);addView(packageField.tag as View);addView(helper("Automate integration fills these values automatically. Turn it off above to use a custom receiver."))})
        useAutomateSwitch.setOnCheckedChangeListener{_,checked->applyReceiverState(checked)};applyReceiverState(useAutomateSwitch.isChecked)
        root.addView(sectionTitle("Buttons & pages"));root.addView(sectionCard().apply{addView(helper("${mode.pages.size} page${if(mode.pages.size==1)"" else "s"} · 6 buttons per page"));addView(Button(this@SettingsActivity).apply{text="EDIT BUTTONS & PAGES";setTextColor(AppColors.Text);setTypeface(typeface,Typeface.BOLD);isAllCaps=false;background=rippleBackground(AppColors.SurfaceRaised,14,AppColors.Border);setOnClickListener{if(saveSettingsOnly())startActivity(Intent(this@SettingsActivity,PageManagerActivity::class.java).putExtra("mode_index",modeIndex))}},LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,dp(50)).apply{topMargin=dp(8)})})
        root.addView(sectionTitle("Driving screen"));root.addView(sectionCard().apply{vibrationSwitch=switchRow("Vibrate when commands are sent",global.vibration);awakeSwitch=switchRow("Keep the screen awake",global.keepScreenAwake);addView(vibrationSwitch);addView(awakeSwitch)})
        root.addView(Button(this).apply{text="RESET THIS MODE";isAllCaps=false;setTextColor(AppColors.Text);setTypeface(typeface,Typeface.BOLD);background=rippleBackground(AppColors.Danger,16);setOnClickListener{AlertDialog.Builder(this@SettingsActivity).setTitle("Reset ${mode.name}?").setMessage("This removes this mode's pages, button commands and settings.").setNegativeButton("CANCEL",null).setPositiveButton("RESET"){_,_->AppPrefs.resetMode(this@SettingsActivity,modeIndex);render()}.show()}},LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,dp(52)).apply{topMargin=dp(10);bottomMargin=dp(18)});setContentView(scroll)}
    private fun applyReceiverState(useAutomate:Boolean){listOf(actionField,extraKeyField,packageField).forEach{it.isEnabled=!useAutomate;(it.tag as View).alpha=if(useAutomate).45f else 1f};automateHelpButton.visibility=if(useAutomate)View.VISIBLE else View.GONE}
    private fun showAutomateSetupDialog(){val message="""BigButtons is preconfigured for Automate.\n\nIn Automate:\n\n1. Add a Broadcast receive block.\n2. Set Action to:\n   com.bigbuttons.COMMAND\n3. Set Broadcast extras output to:\n   extras\n4. Start the flow.\n\nYour command is available as:\nextras[\"command\"]\n\nFor a quick test, connect Broadcast receive to Toast show and display extras[\"command\"].""";AlertDialog.Builder(this).setTitle("Connect Automate").setMessage(message).setNegativeButton("CLOSE",null).setPositiveButton("SEND TEST"){_,_->try{CommandDispatcher.send(this,modeIndex,AppPrefs.mode(this,modeIndex).copy(useAutomateIntegration=true),"bigbuttons_test","test");Toast.makeText(this,"Test command sent",Toast.LENGTH_SHORT).show()}catch(e:Exception){Toast.makeText(this,e.message?:"Could not send test command",Toast.LENGTH_LONG).show()}}.show()}
    private fun saveSettingsOnly():Boolean{val name=nameField.text.toString().trim();val action=actionField.text.toString().trim();val key=extraKeyField.text.toString().trim();if(name.isBlank()){nameField.error="Mode name is required";return false};if(!useAutomateSwitch.isChecked&&action.isBlank()){actionField.error="Broadcast action is required";return false};if(!useAutomateSwitch.isChecked&&key.isBlank()){extraKeyField.error="Command key is required";return false};val existing=AppPrefs.mode(this,modeIndex);AppPrefs.saveMode(this,modeIndex,existing.copy(name=name,useAutomateIntegration=useAutomateSwitch.isChecked,broadcastAction=action,extraKey=key,targetPackage=packageField.text.toString().trim(),startupEnabled=startupEnabledSwitch.isChecked,wakeTarget=wakeTargetSwitch.isChecked,startupDelayMs=startupDelayField.text.toString().trim().toIntOrNull()?.coerceIn(0,5000)?:900,startupCommand=startupCommandField.text.toString().trim(),returnToBigButtons=returnSwitch.isChecked));AppPrefs.saveGlobal(this,GlobalConfig(vibrationSwitch.isChecked,awakeSwitch.isChecked));return true}
    private fun sectionTitle(t:String)=TextView(this).apply{text=t;makeSectionTitle();setPadding(0,dp(12),0,dp(7))}
    private fun sectionCard()=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(14),dp(12),dp(14),dp(12));background=roundedBackground(AppColors.Surface,18,AppColors.Border);layoutParams=LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,LinearLayout.LayoutParams.WRAP_CONTENT).apply{bottomMargin=dp(10)}}
    private fun field(label:String,value:String,helper:String?=null,numeric:Boolean=false):EditText{val wrap=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};wrap.addView(TextView(this).apply{text=label;setTextColor(AppColors.Text);textSize=13f;setTypeface(typeface,Typeface.BOLD);setPadding(0,dp(5),0,dp(2))});val f=EditText(this).apply{setText(value);setTextColor(AppColors.Text);setHintTextColor(AppColors.Muted);textSize=16f;inputType=if(numeric)InputType.TYPE_CLASS_NUMBER else InputType.TYPE_CLASS_TEXT or InputType.TYPE_TEXT_FLAG_NO_SUGGESTIONS;setSingleLine(true);setPadding(dp(8),dp(5),dp(8),dp(5));backgroundTintList=ColorStateList.valueOf(AppColors.Muted)};wrap.addView(f,LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,dp(48)));if(!helper.isNullOrBlank())wrap.addView(TextView(this).apply{text=helper;setTextColor(AppColors.Muted);textSize=12f;setPadding(0,0,0,dp(5))});f.tag=wrap;return f}
    private fun switchRow(label:String,checked:Boolean)=Switch(this).apply{text=label;isChecked=checked;setTextColor(AppColors.Text);textSize=15f;setPadding(0,dp(5),0,dp(5))}
    private fun helper(t:String)=TextView(this).apply{text=t;setTextColor(AppColors.Muted);textSize=13f;setPadding(0,dp(4),0,dp(4))}
}
